Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -49,15 +49,20 @@ jobs:
       - name: Build APK
         run: ./gradlew assembleRelease
 
+      - name: Verify APK location
+        run: |
+          ls app/build/outputs/apk/release/
+
       - name: Create ZIP file with APK
         run: |
-          
-          ZIP_NAME="${{ env.ZIP_NAME }}"
-          cp app/build/outputs/apk/release/app-release.apk $ZIP_NAME  # ZIP化する対象のapkをコピー
-
-          
-          zip "$ZIP_NAME" app-release.apk
-          rm app-release.apk
+          if [ -f "app/build/outputs/apk/release/app-release.apk" ]; then
+            echo "APK found, creating ZIP..."
+            ZIP_NAME="${{ env.ZIP_NAME }}"
+            zip "$ZIP_NAME" app/build/outputs/apk/release/app-release.apk
+          else
+            echo "APK file not found, exiting."
+            exit 1
+          fi
 
       - name: Upload the generated ZIP file as an artifact
         uses: actions/upload-artifact@v4
